create: fix iscsi iqn validation check error
ERROR: target iqn creation failed for: sample/block1 [at block_svc_routines.c+3959 :<blockValidateCommandOutput>]
INFO: command exit code, -1 [at block_svc_routines.c+4366 :<block_create_common>]

The string will be "Created target iqn.2016-12.org.gluster-block::34c5d642-338a-4782-b595-f0dfc33d5c34."

This was introuduced by commit 0722750be4b1f064.

Signed-off-by: Xiubo Li <xiubli@redhat.com>
Reviewed-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>