upgrade_activities: always wait till the background daemon is terminated
When the upgrade activities script finishes and exit successfully,
the gluster-blockd daemon running in the background may still not
killed, so this will be a problem when the gluster-block service
try to start:

ERROR: gluster-blockd is already running...

And also when running the gluster-blockd daemon in background it
may need a while to get fired, so here will always try 5 times by
waiting 1 second each time.

Signed-off-by: Xiubo Li <xiubli@redhat.com>
Reviewed-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>