fix compile error
Looks like the glfs_ftruncate api changed to include extra arguments.
This caused the following error while compiling:
glfs-operations.c:215:11: error: too few arguments to function ‘glfs_ftruncate’

Fixed it.

Signed-off-by: Ravishankar N <ravishankar@redhat.com>