spec: fix rpms build errors
Problems:
--------
$ make rpms
[...]
warning: bogus date in %changelog: Sun Apr 3 2019
error: %changelog not in descending chronological order
make: *** [rpms] Error 1

/usr/bin/install -c -m 644 gluster-block.logrotate               \
	/data/gluster-block/build/rpmbuild/BUILDROOT/gluster-block-0.3-1.x86_64/etc/logrotate.d/gluster-block;
/usr/bin/install: cannot stat 'gluster-block.logrotate': No such file or directory

Solution:
--------
Correct the date in the changelog and update the date to when the
PR is merged.

Signed-off-by: Xiubo Li <xiubli@redhat.com>
Reviewed-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>